### PR TITLE
Dev team

### PR DESCRIPTION
**Pull request by TimeString**
I've implemented the team features. It's a big change and please let me know if anything looks weird.

### CODE REVIEW

**Comment by Klamath233** [comment]
Where do you define the database migrations? (E.g. addition of columns, etc)

**Comment by PARanOiA1120** [comment]
@Klamath233 Should be in this file embed_grader/serapis/models.py

**Comment by Klamath233** [comment]
Create team/Join Team link should make hovering cursor to change to a hand instead of an insertion cursor.

**Comment by Klamath233** [comment]
- [ ] csrf token is needed in the new Join Team form in assignment.html or a 403 forbidden will be returned.
- [ ] add_users_to_team method should contain another argument "assignment" or there will be undefined references in line 68 of team_helper.py
- [ ] JoinTeamForm.is_valid() will return False while the Join Team action is saved to the database.

**Comment by Klamath233** [comment]
I've pushed some fixes. Plz check.

**Comment by TimeString** [comment]
- [ ] Didn't handle when one drops a course

**Pull request merged**
